# Generated by Django 3.2 on 2021-05-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('preco', models.CharField(max_length=254, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, max_length=254, verbose_name='Descrição')),
                ('estado', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado')], max_length=50, verbose_name='Estado')),
            ],
        ),
    ]
